---
title: "facefuns Overview"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{facefuns Overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Convenience functions

Function name | Brief description 
:-------- | :---------------------------------------------------------------------- 
`facefuns` | Conducts GPA and PCA, selects and creates PCs for plotting of 2-D and 3-D data
`read_lmdata` | Read landmark data from TPS, webmorph_list or Webmorph template files
`read_vertices` | Read vertex data from PLY and OBJ files
`select_pcs` | Select PCs based on *broken stick*, *Kaiser Guttman* or *total variance explained* criterion 
`make_pcs` | Creates coordinates for a reference face at +/- x units of standard deviations for a (list of) given principal component(s) 
`plot_2dpcs` | Create TPS grid plots for 2-D PCs
`plot_3dpcs` | Create plots for 3-D PCs
`mirror_templates` | Mirror landmark templates
`symm_templates` | Symmetrise landmark templates

## Shape metrics
Functions for calculating commonly derived morphometric descriptives

Function name | Brief description | Vignette
:-------- | :---------------------------------------------------------------------- | :-------- 
`calc_avg` | Calculate averageness (reversed distance between original template(s) and sample average) | [calcED](./calcSD.html)
`calc_as` | Calculate asymmetry (distance between original and symmetrized template) | [calcAsym](./calcAsym.html)
`calc_fa` | Calculate fluctuating asymmetry (distance between FA component and symmetric average) | [calcAsym](./calcAsym.html)
`calc_ed` | Calculate Euclidean distance | [calcED](./calcED.html)
`calc_ds` | Calculate group membership based on linear discriminant analysis | [calcSD](./calcSD.html)
`calc_shapevs` | Calculate group membership based on vector projection (from facefuns object, allows for symmetrizing of templates) | [calcSD](./calcSD.html)
`calc_vs` | Calculate group membership based on vector projection (from PC scores) | [calcSD](./calcSD.html)

## Utility functions
Functions for formatting data

Function name | Brief description | Vignette
:-------- | :---------------------------------------------------------------------- | :-------- 
`bind_arrays` | Bind two 3-D arrays
`convert_array_to_matrix` | Convert 3-D array to 2-D matrix
`convert_points_to_mesh` | Convert matrix of 3-D coordinates to 3-D mesh
`convert_tem_to_tps` | Read Webmorph template files and save as TPS

## Example data
Data included in `facefuns`

Data | Content 
:------ | :------ 
`LondonSet_data` | FRL London set: original templates (p=132, k=2, n=102) 
`LondonSet_aligned` | FRL London set: Procrustes-aligned templates (p=132, k=2, n=102) 
`LondonSet_scores` | FRL London set: principal component scores (first eight PCs) 
`LondonSet_info` | FRL London set: basic demographic data  
`mirroredlandmarks` | FRL London set: order of mirrored landmarks (p=132)  
